export const CINEMAS_REQUESTED = 'CINEMAS_REQUESTED';
export const CINEMAS_RECEIVED = 'CINEMAS_RECEIVED';
export const CINEMA_SELECTED = 'CINEMA_SELECTED';
export const CINEMA_UNSELECTED = 'CINEMA_UNSELECTED';
export const MOVIE_SESSIONS_REQUESTED = 'MOVIE_SESSIONS_REQUESTED';
export const MOVIE_SESSIONS_RECEIVED = 'MOVIE_SESSIONS_RECEIVED';
export const MOVIE_SESSIONS_STATE_CLEARED = 'MOVIE_SESSIONS_STATE_CLEARED';
