export const MOVIES_REQUESTED = 'MOVIES_REQUESTED';
export const MOVIES_RECEIVED = 'MOVIES_RECEIVED';
export const MOVIES_REQUEST_FAILED = 'MOVIES_REQUEST_FAILED';
export const CLEAR_ERROR = 'CLEAR_ERROR';

