export const MOVIE_DETAILS_RECEIVED = 'MOVIE_DETAILS_RECEIVED';
export const MOVIE_DETAILS_REQUESTED = 'MOVIE_DETAILS_REQUESTED';
export const MOVIE_SELECTED = 'MOVIE_SELECTED';
export const MOVIE_DETAILS_STATE_CLEARED = 'MOVIE_DETAILS_STATE_CLEARED';
