export const MOVIE_DETAILS_RECEIVED = 'MOVIE_DETAILS_RECEIVED';
export const MOVIE_DETAILS_REQUESTED = 'MOVIE_DETAILS_REQUESTED';
export const MOVIE_SELECTED = 'MOVIE_SELECTED';
export const CLEAR_MOVIE_DETAILS_STATE = 'CLEAR_MOVIE_DETAILS_STATE';
