export const SELECT_MOVIE_SESSION = 'SELECT_MOVIE_SESSION';
export const ADD_SEAT = 'ADD_SEAT';
export const REMOVE_SEAT = 'REMOVE_SEAT';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const INCREMENT_ADDITION = 'INCREMENT_ADDITION';
export const DECREMENT_ADDITION = 'DECREMENT_ADDITION';

